spring:
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.1"
      database: "batchProcess"
  batch:
    job:
      enabled: false
