version: '3.8'

services:
  mongo:
    image: mongo:8.0.5
    container_name: mongodb_rs
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
        sleep 5 &&
        mongosh --host mongo:27017 --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"localhost:27017\" }]
          })
        '
      "
    

volumes:
  mongo-data:
